import type { Metadata } from "next";
import '@/app/reset.css'
import type { PropsWithChildren} from "react";
import React from 'react';
import AntDesignProvider from "@/Providers/AntDesignProvider/AntDesignProvider";
import ErrorPage from './error/page';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ru">
      <body>

      <React.StrictMode>
          <ErrorPage />
      </React.StrictMode>

      {/*<AntDesignProvider>*/}
      {/*    {children}*/}
      {/*</AntDesignProvider>*/}
      </body>
    </html>
  );
}
