import type { Metadata } from "next";
import '@/app/reset.css'
import type { PropsWithChildren} from "react";
import React from 'react';
import Sidebar from '@/components/Universal/Sidebar/Sidebar';
import AntDesignProvider from "@/Providers/AntDesignProvider/AntDesignProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ru">
      <body>
          <AntDesignProvider>
              <Sidebar />
              <div>{children}</div>
          </AntDesignProvider>
      </body>
    </html>
  );
}
